### ISSUE TITLE
Swift 1.1

### ISSUE THREAD

**Issue by davut5** [ooper-shlab/AVAEMixerSample1.0-Swift#2]
hi my friend. i want to use this sample. but my project has written Swift 1.1.  but this sample swift 2.0
can you send me swift 1 or 1.2
davuttemel34@gmail.com

**Comment by davut5** [comment]
please ooper-shlab. i am waiting you. i need it to much.

**Comment by ooper-shlab** [comment]
Thanks for being interested in my translation.
But, sorry, the translation was made when Swift was already got 1.2, and I have no 1.1 version.

**Comment by davut5** [comment]
oh ok send me swift 1.2 ?

**Comment by ooper-shlab** [comment]
I won't make a personal contact through GitHub, but I tagged the latest Swift 1.2 compatible version. You can download it through Releases/Tags of the repository, or you can retrieve it from the clone.

**Comment by davut5** [comment]
oh my friend  i download project but There are too many files inside.(objectiv-c files) Is all this necessary.It is the most simple. My request is not finished yet sorry excuse any.

**Comment by ooper-shlab** [comment]
All Objective-C files are just there to find how Objective-C code translated into Swift. Open the project and remove all .h & .m files, I believe you can build the project without them. Or you can use any parts of the Swift code just ignoring them.

**Comment by davut5** [comment]
oh man  now working fine.. You're very helpful. Thank you very much

**Comment by davut5** [comment]
i want to ask you last question?. i use Youtube Helper pods. my goal recording youtube player sound (instead of marimbaLoop) and  my voice mix. Can i make?

**Comment by ooper-shlab** [comment]
I'm just sort of Swift geek and you'd better ask somewhere iOS experts are watching. But if I were asked by my client, I would answer it was very hard and possibly impossible. You see, it's beyond my knowledge or experience.

**Comment by davut5** [comment]
Oh Ok . Thank you for your interest.
